---
#
# Install/run fluentd
#

- name: Setup Fluentd Repository (RedHat/Rocky)
  when: ansible_os_family == "RedHat"
  become: true
  block:
    - name: Copy fluentd yum repo file
      ansible.builtin.copy:
        src: fluentd.repo
        dest: /etc/yum.repos.d/fluentd.repo
        owner: root
        group: root
        mode: '0644'

    - name: Import fluentd GPG Key
      ansible.builtin.rpm_key:
        key: https://packages.treasuredata.com/GPG-KEY-td-agent
        state: present

    - name: Install fluentd and dependencies
      ansible.builtin.dnf:
        name:
          - td-agent
          - gcc
        state: present

- name: Setup Fluentd Repository (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  become: true
  block:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - curl
          - gnupg2
          - lsb-release
          - build-essential
        state: present
        update_cache: true

    - name: Add Fluentd GPG key
      ansible.builtin.apt_key:
        url: https://packages.treasuredata.com/GPG-KEY-td-agent
        state: present

    - name: Add Fluentd repository
      ansible.builtin.apt_repository:
      repo: >-
       deb https://packages.treasuredata.com/4/{{ ansible_distribution | lower }}/{{ ansible_distribution_release }}/
       {{ ansible_distribution_release }} contrib
       state: present
       filename: fluentd
   
    - name: Install fluentd
      ansible.builtin.apt:
        name: td-agent
        state: present

- name: Setup fluentd configuration files
  ansible.builtin.template:
    src: td-agent.conf.j2
    dest: /etc/td-agent/td-agent.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  register: fluentd_config

# Compatibility tasks (RedHat specific paths)
- name: Configure OpenSSL (RedHat Family)
  when: ansible_os_family == "RedHat"
  become: true
  block:
    - name: Load OpenSSL CA Extended Configuration
      ansible.builtin.template:
        src: openssl_extras.cnf.j2
        dest: /etc/pki/tls/openssl_extras.cnf
        owner: root
        group: root
        mode: '0644'

    - name: Check OpenSSL SANs (SubjectAltName) entry for CA
      ansible.builtin.shell: |
        grep "{{ ansible_default_ipv4.address }}" /etc/pki/tls/openssl.cnf | wc -l
      register: subject_alt_name_exists
      changed_when: false
      failed_when: false

    - name: Add OpenSSL SANs (SubjectAltName) entry for CA
      ansible.builtin.lineinfile:
        dest: /etc/pki/tls/openssl.cnf
        line: 'subjectAltName = "IP: {{ ansible_default_ipv4.address }}"'
        regexp: '^ Extensions for a typical CA'
        insertbefore: '# Extensions for a typical CA'
        backup: yes
      when: subject_alt_name_exists.stdout | int == 0

- name: Install fluentd elasticsearch plugin
  community.general.gem:
    name: fluent-plugin-elasticsearch
    state: latest
    include_dependencies: yes
    user_install: no
    executable: /usr/sbin/td-agent-gem
  become: true

- name: Install fluentd beats plugin
  community.general.gem:
    name: fluent-plugin-beats
    state: latest
    include_dependencies: yes
    user_install: no
    executable: /usr/sbin/td-agent-gem
  become: true

- name: Load filebeat JSON index template
  ansible.builtin.uri:
    url: http://localhost:9200/_template/filebeat?pretty
    method: POST
    body: "{{ lookup('file', 'filebeat-index-template.json') }}"
    body_format: json
  ignore_errors: true
  become: true

- name: Start and enable fluentd service
  ansible.builtin.service:
    name: td-agent
    state: started
    enabled: true
  become: true

- name: Restart fluentd if config changed
  ansible.builtin.service:
    name: td-agent
    state: restarted
  when: fluentd_config.changed
  become: true
