---
#
# install/run filebeat elk client
#
- name: Install Python3 (EL8+)
  ansible.builtin.package:
    name: python3
    state: present
  become: true
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int >= 8

- name: Install filebeat package
  ansible.builtin.package:
    name: filebeat
    state: present
  become: true
  when: effective_logging_backend != 'fluentd'

- name: Generate filebeat configuration template
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: '0644'
  become: true
  when: effective_logging_backend != 'fluentd'
  register: filebeat_config

- name: Ensure filebeat service is started and enabled
  ansible.builtin.service:
    name: filebeat
    state: started
    enabled: true
  become: true
  when: effective_logging_backend != 'fluentd'

- name: Restart filebeat if configuration changed
  ansible.builtin.service:
    name: filebeat
    state: restarted
  become: true
  when:
    - effective_logging_backend != 'fluentd'
    - filebeat_config.changed

- name: Install rsyslog package
  ansible.builtin.package:
    name: rsyslog
    state: present
  become: true
  when: effective_logging_backend == 'fluentd'

- name: Setup rsyslogd for fluentd
  ansible.builtin.lineinfile:
    dest: /etc/rsyslog.conf
    line: "*.* @{{ elk_server }}:{{ fluentd_syslog_port }}"
    state: present
  become: true
  when: effective_logging_backend == 'fluentd'
  register: rsyslog_main_config

- name: Setup common OpenStack rsyslog logging
  ansible.builtin.template:
    src: rsyslog-openstack.conf.j2
    dest: /etc/rsyslog.d/openstack-logs.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  when: effective_logging_backend == 'fluentd'
  register: rsyslog_openstack_config

- name: Restart rsyslog if configuration changed
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  become: true
  when:
    - effective_logging_backend == 'fluentd'
    - rsyslog_main_config.changed or rsyslog_openstack_config.changed
